"""Move phone and location from users to profiles, make user-profile 1-to-1

Revision ID: 02fc498d11ed
Revises: a813910eae98
Create Date: 2025-08-13 16:53:10.792486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02fc498d11ed'
down_revision: Union[str, Sequence[str], None] = 'a813910eae98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('location', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'profiles', ['user_id'])
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'profiles', type_='unique')
    op.drop_column('profiles', 'location')
    op.drop_column('profiles', 'phone_number')
    # ### end Alembic commands ###
