"""Add password_hash and email index to users

Revision ID: 53d8bb845b30
Revises: 5adc69a5fade
Create Date: 2025-08-09 20:46:03.962989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53d8bb845b30'
down_revision: Union[str, Sequence[str], None] = '5adc69a5fade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('custom_sections', 'profile_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=False))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'password_hash')
    op.alter_column('custom_sections', 'profile_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
