"""Add email column to profiles table

Revision ID: 6eac5e04617a
Revises: 02fc498d11ed
Create Date: 2025-08-13 16:57:13.035098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eac5e04617a'
down_revision: Union[str, Sequence[str], None] = '02fc498d11ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'email')
    # ### end Alembic commands ###
