"""implement inheritance based global entity system

Revision ID: 013fc9c3a89b
Revises: 4d381a20854c
Create Date: 2025-08-08 16:57:43.765426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '013fc9c3a89b'
down_revision: Union[str, Sequence[str], None] = '4d381a20854c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificates', sa.Column('entity_id', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'certificates', ['entity_id'])
    op.add_column('education', sa.Column('entity_id', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'education', ['entity_id'])
    op.add_column('generated_resumes', sa.Column('entity_id', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'generated_resumes', ['entity_id'])
    op.add_column('job_descriptions', sa.Column('entity_id', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'job_descriptions', ['entity_id'])
    op.add_column('languages', sa.Column('entity_id', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'languages', ['entity_id'])
    op.add_column('professional_summaries', sa.Column('entity_id', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'professional_summaries', ['entity_id'])
    op.add_column('profile_links', sa.Column('entity_id', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'profile_links', ['entity_id'])
    op.add_column('projects', sa.Column('entity_id', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'projects', ['entity_id'])
    op.add_column('skills', sa.Column('entity_id', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'skills', ['entity_id'])
    op.add_column('vector_embeddings', sa.Column('entity_id', sa.UUID(), nullable=False))
    op.create_index('idx_vector_embeddings_entity', 'vector_embeddings', ['entity_id'], unique=False)
    op.create_index('idx_vector_embeddings_qdrant', 'vector_embeddings', ['qdrant_point_id'], unique=False)
    op.drop_constraint(op.f('vector_embeddings_education_id_fkey'), 'vector_embeddings', type_='foreignkey')
    op.drop_constraint(op.f('vector_embeddings_work_experience_id_fkey'), 'vector_embeddings', type_='foreignkey')
    op.drop_constraint(op.f('vector_embeddings_certificate_id_fkey'), 'vector_embeddings', type_='foreignkey')
    op.drop_constraint(op.f('vector_embeddings_project_id_fkey'), 'vector_embeddings', type_='foreignkey')
    op.drop_constraint(op.f('vector_embeddings_language_id_fkey'), 'vector_embeddings', type_='foreignkey')
    op.drop_constraint(op.f('vector_embeddings_skill_id_fkey'), 'vector_embeddings', type_='foreignkey')
    op.drop_constraint(op.f('vector_embeddings_professional_summary_id_fkey'), 'vector_embeddings', type_='foreignkey')
    op.drop_constraint(op.f('vector_embeddings_job_description_id_fkey'), 'vector_embeddings', type_='foreignkey')
    op.drop_constraint(op.f('vector_embeddings_profile_id_fkey'), 'vector_embeddings', type_='foreignkey')
    op.drop_constraint(op.f('vector_embeddings_custom_section_id_fkey'), 'vector_embeddings', type_='foreignkey')
    op.drop_constraint(op.f('vector_embeddings_generated_resume_id_fkey'), 'vector_embeddings', type_='foreignkey')
    op.drop_constraint(op.f('vector_embeddings_profile_link_id_fkey'), 'vector_embeddings', type_='foreignkey')
    op.drop_column('vector_embeddings', 'generated_resume_id')
    op.drop_column('vector_embeddings', 'professional_summary_id')
    op.drop_column('vector_embeddings', 'profile_id')
    op.drop_column('vector_embeddings', 'certificate_id')
    op.drop_column('vector_embeddings', 'job_description_id')
    op.drop_column('vector_embeddings', 'custom_section_id')
    op.drop_column('vector_embeddings', 'education_id')
    op.drop_column('vector_embeddings', 'skill_id')
    op.drop_column('vector_embeddings', 'language_id')
    op.drop_column('vector_embeddings', 'profile_link_id')
    op.drop_column('vector_embeddings', 'work_experience_id')
    op.drop_column('vector_embeddings', 'project_id')
    op.add_column('work_experiences', sa.Column('entity_id', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'work_experiences', ['entity_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work_experiences', type_='unique')
    op.drop_column('work_experiences', 'entity_id')
    op.add_column('vector_embeddings', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('vector_embeddings', sa.Column('work_experience_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('vector_embeddings', sa.Column('profile_link_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('vector_embeddings', sa.Column('language_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('vector_embeddings', sa.Column('skill_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('vector_embeddings', sa.Column('education_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('vector_embeddings', sa.Column('custom_section_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('vector_embeddings', sa.Column('job_description_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('vector_embeddings', sa.Column('certificate_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('vector_embeddings', sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('vector_embeddings', sa.Column('professional_summary_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('vector_embeddings', sa.Column('generated_resume_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('vector_embeddings_profile_link_id_fkey'), 'vector_embeddings', 'profile_links', ['profile_link_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('vector_embeddings_generated_resume_id_fkey'), 'vector_embeddings', 'generated_resumes', ['generated_resume_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('vector_embeddings_custom_section_id_fkey'), 'vector_embeddings', 'custom_sections', ['custom_section_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('vector_embeddings_profile_id_fkey'), 'vector_embeddings', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('vector_embeddings_job_description_id_fkey'), 'vector_embeddings', 'job_descriptions', ['job_description_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('vector_embeddings_professional_summary_id_fkey'), 'vector_embeddings', 'professional_summaries', ['professional_summary_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('vector_embeddings_skill_id_fkey'), 'vector_embeddings', 'skills', ['skill_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('vector_embeddings_language_id_fkey'), 'vector_embeddings', 'languages', ['language_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('vector_embeddings_project_id_fkey'), 'vector_embeddings', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('vector_embeddings_certificate_id_fkey'), 'vector_embeddings', 'certificates', ['certificate_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('vector_embeddings_work_experience_id_fkey'), 'vector_embeddings', 'work_experiences', ['work_experience_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('vector_embeddings_education_id_fkey'), 'vector_embeddings', 'education', ['education_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_vector_embeddings_qdrant', table_name='vector_embeddings')
    op.drop_index('idx_vector_embeddings_entity', table_name='vector_embeddings')
    op.drop_column('vector_embeddings', 'entity_id')
    op.drop_constraint(None, 'skills', type_='unique')
    op.drop_column('skills', 'entity_id')
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_column('projects', 'entity_id')
    op.drop_constraint(None, 'profile_links', type_='unique')
    op.drop_column('profile_links', 'entity_id')
    op.drop_constraint(None, 'professional_summaries', type_='unique')
    op.drop_column('professional_summaries', 'entity_id')
    op.drop_constraint(None, 'languages', type_='unique')
    op.drop_column('languages', 'entity_id')
    op.drop_constraint(None, 'job_descriptions', type_='unique')
    op.drop_column('job_descriptions', 'entity_id')
    op.drop_constraint(None, 'generated_resumes', type_='unique')
    op.drop_column('generated_resumes', 'entity_id')
    op.drop_constraint(None, 'education', type_='unique')
    op.drop_column('education', 'entity_id')
    op.drop_constraint(None, 'certificates', type_='unique')
    op.drop_column('certificates', 'entity_id')
    # ### end Alembic commands ###
