"""Add missing profile columns

Revision ID: 161dae5f5a29
Revises: 6eac5e04617a
Create Date: 2026-03-19 21:56:18.914045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '161dae5f5a29'
down_revision: Union[str, Sequence[str], None] = '6eac5e04617a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('headline', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('summary', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('specializations', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('career_objectives', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'career_objectives')
    op.drop_column('profiles', 'specializations')
    op.drop_column('profiles', 'summary')
    op.drop_column('profiles', 'headline')
    # ### end Alembic commands ###
