"""add degree_type to education and rename issuer to issuing_organization in certificates

Revision ID: 334db2b5be54
Revises: 4a99f61eeba4
Create Date: 2026-03-20 01:16:08.554413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '334db2b5be54'
down_revision: Union[str, Sequence[str], None] = '4a99f61eeba4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificates', sa.Column('issuing_organization', sa.String(), nullable=True))
    op.drop_column('certificates', 'issuer')
    op.add_column('education', sa.Column('degree_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('education', 'degree_type')
    op.add_column('certificates', sa.Column('issuer', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('certificates', 'issuing_organization')
    # ### end Alembic commands ###
