"""add can_read can_write can_speak to languages

Revision ID: 4a99f61eeba4
Revises: a395d25ba910
Create Date: 2026-03-20 01:15:08.293301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a99f61eeba4'
down_revision: Union[str, Sequence[str], None] = 'a395d25ba910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('languages', sa.Column('can_read', sa.Boolean(), nullable=True))
    op.add_column('languages', sa.Column('can_write', sa.Boolean(), nullable=True))
    op.add_column('languages', sa.Column('can_speak', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('languages', 'can_speak')
    op.drop_column('languages', 'can_write')
    op.drop_column('languages', 'can_read')
    # ### end Alembic commands ###
