"""Add proper foreign key relationships to vector_embeddings

Revision ID: 4d381a20854c
Revises: a86c4bf958f7
Create Date: 2025-08-08 16:37:30.879565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d381a20854c'
down_revision: Union[str, Sequence[str], None] = 'a86c4bf958f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vector_embeddings', sa.Column('profile_id', sa.Integer(), nullable=True))
    op.add_column('vector_embeddings', sa.Column('job_description_id', sa.Integer(), nullable=True))
    op.add_column('vector_embeddings', sa.Column('generated_resume_id', sa.Integer(), nullable=True))
    op.add_column('vector_embeddings', sa.Column('work_experience_id', sa.Integer(), nullable=True))
    op.add_column('vector_embeddings', sa.Column('project_id', sa.Integer(), nullable=True))
    op.add_column('vector_embeddings', sa.Column('education_id', sa.Integer(), nullable=True))
    op.add_column('vector_embeddings', sa.Column('skill_id', sa.Integer(), nullable=True))
    op.add_column('vector_embeddings', sa.Column('certificate_id', sa.Integer(), nullable=True))
    op.add_column('vector_embeddings', sa.Column('language_id', sa.Integer(), nullable=True))
    op.add_column('vector_embeddings', sa.Column('professional_summary_id', sa.Integer(), nullable=True))
    op.add_column('vector_embeddings', sa.Column('profile_link_id', sa.Integer(), nullable=True))
    op.add_column('vector_embeddings', sa.Column('custom_section_id', sa.Integer(), nullable=True))
    op.add_column('vector_embeddings', sa.Column('embedding_type', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'vector_embeddings', ['qdrant_point_id'])
    op.create_foreign_key(None, 'vector_embeddings', 'certificates', ['certificate_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'vector_embeddings', 'job_descriptions', ['job_description_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'vector_embeddings', 'profile_links', ['profile_link_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'vector_embeddings', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'vector_embeddings', 'work_experiences', ['work_experience_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'vector_embeddings', 'professional_summaries', ['professional_summary_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'vector_embeddings', 'custom_sections', ['custom_section_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'vector_embeddings', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'vector_embeddings', 'education', ['education_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'vector_embeddings', 'skills', ['skill_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'vector_embeddings', 'languages', ['language_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'vector_embeddings', 'generated_resumes', ['generated_resume_id'], ['id'], ondelete='CASCADE')
    op.drop_column('vector_embeddings', 'entity_type')
    op.drop_column('vector_embeddings', 'entity_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vector_embeddings', sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('vector_embeddings', sa.Column('entity_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'vector_embeddings', type_='foreignkey')
    op.drop_constraint(None, 'vector_embeddings', type_='foreignkey')
    op.drop_constraint(None, 'vector_embeddings', type_='foreignkey')
    op.drop_constraint(None, 'vector_embeddings', type_='foreignkey')
    op.drop_constraint(None, 'vector_embeddings', type_='foreignkey')
    op.drop_constraint(None, 'vector_embeddings', type_='foreignkey')
    op.drop_constraint(None, 'vector_embeddings', type_='foreignkey')
    op.drop_constraint(None, 'vector_embeddings', type_='foreignkey')
    op.drop_constraint(None, 'vector_embeddings', type_='foreignkey')
    op.drop_constraint(None, 'vector_embeddings', type_='foreignkey')
    op.drop_constraint(None, 'vector_embeddings', type_='foreignkey')
    op.drop_constraint(None, 'vector_embeddings', type_='foreignkey')
    op.drop_constraint(None, 'vector_embeddings', type_='unique')
    op.drop_column('vector_embeddings', 'embedding_type')
    op.drop_column('vector_embeddings', 'custom_section_id')
    op.drop_column('vector_embeddings', 'profile_link_id')
    op.drop_column('vector_embeddings', 'professional_summary_id')
    op.drop_column('vector_embeddings', 'language_id')
    op.drop_column('vector_embeddings', 'certificate_id')
    op.drop_column('vector_embeddings', 'skill_id')
    op.drop_column('vector_embeddings', 'education_id')
    op.drop_column('vector_embeddings', 'project_id')
    op.drop_column('vector_embeddings', 'work_experience_id')
    op.drop_column('vector_embeddings', 'generated_resume_id')
    op.drop_column('vector_embeddings', 'job_description_id')
    op.drop_column('vector_embeddings', 'profile_id')
    # ### end Alembic commands ###
