"""update profile_links and projects schema

Revision ID: 550ae3b4a7b9
Revises: 985578ef3c6d
Create Date: 2026-03-20 00:44:11.493139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '550ae3b4a7b9'
down_revision: Union[str, Sequence[str], None] = '985578ef3c6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_links', sa.Column('label', sa.String(), nullable=True))
    op.add_column('profile_links', sa.Column('link_type', sa.String(), nullable=True))
    op.add_column('profile_links', sa.Column('is_visible', sa.Boolean(), nullable=True))
    op.drop_column('profile_links', 'platform')
    op.add_column('projects', sa.Column('name', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('url', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('technologies', sa.String(), nullable=True))
    op.drop_column('projects', 'project_url')
    op.drop_column('projects', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('project_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('projects', 'technologies')
    op.drop_column('projects', 'url')
    op.drop_column('projects', 'name')
    op.add_column('profile_links', sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('profile_links', 'is_visible')
    op.drop_column('profile_links', 'link_type')
    op.drop_column('profile_links', 'label')
    # ### end Alembic commands ###
