"""remove redundant profile columns

Revision ID: 972a28112e99
Revises: 161dae5f5a29
Create Date: 2026-03-19 22:44:44.693479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '972a28112e99'
down_revision: Union[str, Sequence[str], None] = '161dae5f5a29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'career_objectives')
    op.drop_column('profiles', 'summary')
    op.drop_column('profiles', 'specializations')
    op.drop_column('profiles', 'headline')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('headline', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('specializations', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('summary', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('career_objectives', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
