"""add years_experience to skills

Revision ID: 985578ef3c6d
Revises: add_is_default_summaries
Create Date: 2026-03-20 00:30:05.517298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '985578ef3c6d'
down_revision: Union[str, Sequence[str], None] = 'add_is_default_summaries'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('professional_summaries', 'profile_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('skills', sa.Column('years_experience', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'years_experience')
    op.alter_column('professional_summaries', 'profile_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
