"""add order_index to custom_sections and remove type field

Revision ID: a395d25ba910
Revises: 550ae3b4a7b9
Create Date: 2026-03-20 00:58:22.971423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a395d25ba910'
down_revision: Union[str, Sequence[str], None] = '550ae3b4a7b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_sections', sa.Column('order_index', sa.Integer(), nullable=True))
    op.drop_column('custom_sections', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_sections', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('custom_sections', 'order_index')
    # ### end Alembic commands ###
