"""Add is_active column to users table

Revision ID: c0330b79d13a
Revises: 290bf9bbc390
Create Date: 2025-08-10 22:29:54.104153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0330b79d13a'
down_revision: Union[str, Sequence[str], None] = '290bf9bbc390'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add the column as nullable first
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    
    # Update existing rows to set is_active to True
    op.execute("UPDATE users SET is_active = true WHERE is_active IS NULL")
    
    # Now make the column NOT NULL
    op.alter_column('users', 'is_active', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
