"""rename_profile_link_link_type_to_platform

Revision ID: db5221c039ce
Revises: 334db2b5be54
Create Date: 2026-03-22 01:35:21.333358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db5221c039ce'
down_revision: Union[str, Sequence[str], None] = '334db2b5be54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_links', sa.Column('platform', sa.String(), nullable=True))
    op.drop_column('profile_links', 'link_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_links', sa.Column('link_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('profile_links', 'platform')
    # ### end Alembic commands ###
