"""add unique constraint for profile languages

Revision ID: f52b4d37cafa
Revises: afca4761ba84
Create Date: 2026-03-22 02:35:44.483410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f52b4d37cafa'
down_revision: Union[str, Sequence[str], None] = 'afca4761ba84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_profile_language', 'languages', ['profile_id', 'language'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_profile_language', 'languages', type_='unique')
    # ### end Alembic commands ###
